### PR TITLE
Added folder structure

### PR DESCRIPTION
**Pull request by Bitos88**
Added folder structure

### CODE REVIEW

**Review by alexmaxu — COMMENTED** [review]
Me pare perfectísimo

**Comment by alexmaxu** [comment]
tyutyutyutyutyututyu

**Comment by alexmaxu** [comment]
rtyutyututyut

**Review by alexmaxu — APPROVED** [review]
test 2 ok

**Review by fran-6co — COMMENTED** [review]
ok

**Review by fran-6co — APPROVED** [review]

**Pull request merged**
